### ISSUE TITLE
contador de digitos, 

### ISSUE THREAD

**Issue by javierbarbe** [javierbarbe/repo1#1]
Buenas ivan
al intentar hacer el ejercicio 4 del tema 4 que te pide contar las cifras  lo he hecho con un metodo y un constructor para un tipo de dato int, y no he tenido problema 
al intentar usar el mismo constructor, cambiando el tipo de dato int por double, me da unos resultados muy raros, He probado cambiandolo todo y no llego a ninguna solucion valida.

**Comment by javierbarbe** [comment]
la ruta al codigo es
repo1\ tema4loops\ problemas unidad 4

**Comment by ivanjimenez** [comment]
Javier, especifica tu código con el enlace completo o nombrando la clase, supongo que será esta:
https://github.com/javierbarbe/repo1/blob/master/tema4loops/problemasU4/CuentaDigitos.java

El símbolo / división trunca en enteros pero en double realiza el cálculo. Para contar los dígitos en double tendrás que separar la parte entera y convertirlo a entero y luego hacerlo con la decimal. 

Prueba ese código en jshell para ver cómo funciona y verás que no funciona. Como te comentaba, para contar cifras en un doble hay que extraer parte decimal y entera.
