### ISSUE TITLE
DUDAS EJERCICIO PRIMOS Y SIGUIENTEs

### ISSUE THREAD

**Issue by javierbarbe** [javierbarbe/repo1#3]
Buenas ivan,
el bucle para escribir los cinco siguientes me falla al comprobar  a partir del segundo numero si son los numeros primos o no.

LA RUTA ES:
repo1/tema4loops/problemasU4/Numero5Sig.java 
LA PRUEBA ES:
 repo1/tema4loops/problemasU4/Prueba5Sig.java

**Comment by ivanjimenez** [comment]
Hola, Javier:

   Viendo tu programa estás creando todo el código en el constructor por defecto, no crees que será mejor crear un método que se llame public boolean esPrimo(int n) {...}  tal y como dice el ejercicio?
   
  Por otro lado, creo que te estás complicando la vida un poco con el código. Un número primo es aquel que es divisible por 1 o por si mismo, es decir, que tendrás que comprobar qué números son divisibles por el dado. Es decir el número 7 es primo? 7 es divisible por 7,6,5... etc. Eso tienes que ver.

La otra función es más fácil, pero pertenece a otro ejercicio, ya lo arreglé. Disculpa.

Saludos
