### ISSUE TITLE
laboratorioDuda Constructor COpia

### ISSUE THREAD

**Issue by javierbarbe** [javierbarbe/repo1#7]
Buenas Ivan sigo con dudas con el constructor copia.
He intentado hacer la copia a partir de una instancia dentro del método de copia...
a lo maximo que he llegado es a hacer un puntero, no una copia en sí.
como es un array supongo que para copiarlo habria que usar System.ArrayCopy... pero no funciona

public class ArrayDouble {
Scanner e=new Scanner(System.in);
	private double [] arrayo;
	private int tamanio;
	
	
	public  ArrayDouble () {
		System.out.println("Introduce el tamaño del array");
		 tamanio=e.nextInt();
		arrayo=new double[tamanio];
	
	}
	//constructor que recibe el tamaño del array
	public ArrayDouble(int tamanio) {
		this.tamanio=tamanio;
		arrayo=new double[ this.tamanio];
	}
	//constructor copia
//	public ArrayDouble( ArrayDouble recibido ) {
//		//recibido.arrayo;
//		this.arrayo = recibido.arrayo;
//		
//		ArrayDouble d=new ArrayDouble ();
//		d=System.arraycopy(recibido.arrayo, 0, this.arrayo, 0, tamanio);
//		arrayo=recibido.arrayo;
//		for(int i=0;i<arrayo.length;i++) {
//			//  arrayo[i]=recibido.
//		}
//	}

**Comment by ivanjimenez** [comment]
Hola, Javier

El constructor copia va a copiar el objecto, en tu caso es un array. ¿Qué deberias copiar? Pues el array uno a uno en un simple bucle. No tienes que hacer uso de arrayCopy. En el CC sólo tienes que crear el array con el tamaño que lo coges del array origen y luego haces un bucle. Tienes que tener en cuenta que al crear un objeto con el CC debes tener un objeto creado previamente y pasarlo como parámetro. Luego el CC se encarga de pasar toda la información de un objeto a otro. En el ejemplo de abajo te pongo también un main para que lo compruebes.

```javaimport java.util.Scanner;

public class ArrayDouble {
	Scanner e = new Scanner(System.in);
	private double[] arrayo;
	private int tamanio;

	public ArrayDouble() {
		System.out.println("Introduce el tamaño del array");
		tamanio = e.nextInt();
		arrayo = new double[tamanio];

	}

//constructor que recibe el tamaño del array
	public ArrayDouble(int tamanio) {
		this.tamanio = tamanio;
		arrayo = new double[this.tamanio];
	}
//constructor copia

// public ArrayDouble( ArrayDouble recibido ) {
// //recibido.arrayo;
// this.arrayo = recibido.arrayo;
//
// ArrayDouble d=new ArrayDouble ();
// d=System.arraycopy(recibido.arrayo, 0, this.arrayo, 0, tamanio);
// arrayo=recibido.arrayo;
// for(int i=0;i<arrayo.length;i++) {
// // arrayo[i]=recibido.
// }

	public ArrayDouble(ArrayDouble recibido) {
		
		this.arrayo = new double[recibido.tamanio];
		for (int i = 0; i < recibido.tamanio; i++) {
			this.arrayo[i] = recibido.arrayo[i];
		}
	}
	
	public static void main(String[] args) {
		ArrayDouble temp1 = new ArrayDouble(10);
		
		for(int i=0; i< temp1.tamanio; i++)
			temp1.arrayo[i] = i*2;
//		for(int i=0; i< temp1.tamanio; i++)
//			System.out.println(temp1.arrayo[i]+ " ");
//		
		ArrayDouble temp2 = new ArrayDouble(temp1);
		for(int i=0; i< temp1.tamanio; i++)
			System.out.print(temp2.arrayo[i]+ " ");
		
			


		
	}
}

```
